[FEATURE] Add example for sending HTTP request with Guzzle
TYPO3-Documentation/t3docs-examples pull request #113
Opened 2022-08-31 17:42 UTC by brotkrueml

This example will be used as code snippet for
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Http/Index.html#basic-usage

The main part is the CatFactRequester class which requests a cat fact
from a public API. To hold the example small only the needed code is
available in this class. To really work with the CatFactRequester a
CatFactCommand is introduced which can be called with
`vendor/bin/typo3 examples:catfact` and displays a random fact
about cats.

Resolves: #108

2022-08-31 17:42 UTC, brotkrueml commented on Classes/Http/CatFactRequester.php
> +        return json_decode($response->getBody()->getContents(), true)['fact1']
```suggestion
        return json_decode($response->getBody()->getContents(), true)['fact']
```

2022-08-31 17:43 UTC, brotkrueml commented on Classes/Http/CatFactRequester.php
> +        return json_decode($response->getBody()->getContents(), true)['fact1']
Grr, why can't I apply the change? Forgot to remove the wrong array key from testing.

2022-09-01 08:53 UTC, brotkrueml commented
Interesting, as I don't like and use abbreviations that relation haven't come to my mind ;-) I just thought about the "Requester" suffix, if there may be some other, better word for it.

I can swich to a Chuck Norris API, so `ChuckNorrisJokeRequester` may be the way:
http://api.icndb.com/jokes/random

However, I can't either adjust my PR on GUI neither locally, another push is forbidden for me, maybe some access thingy.

2022-09-01 10:13 UTC, DavidBruchmann commented
> I can swich to a Chuck Norris API, so ChuckNorrisJokeRequester may be the way

Great idea 😂

2022-09-01 13:11 UTC, DavidBruchmann commented
`ChuckRequester` would be enough, but it's your party :laughing:

2022-09-01 16:30 UTC, brotkrueml commented
> `ChuckRequester` would be enough, but it's your party laughing

Stick to the cat but renamed command and requester to MeowInformation. Don't liked the chuck jokes.

2022-09-05 05:44 UTC, linawolf approved these changes

2022-09-06 08:28 UTC, mabolek requested changes

2022-09-17 15:23 UTC, linawolf approved these changes

2022-09-17 15:23 UTC, linawolf commented
@brotkrueml please resolve the conflicts

2022-09-17 15:37 UTC, linawolf commented
There is still a conflict...

2022-09-18 06:44 UTC, linawolf approved these changes

2022-09-18 06:44 UTC, merged