[BUGFIX] [PREPORT] Fix the Github Linkhandler for TYPO3 v11
TYPO3-Documentation/t3docs-examples pull request #133
Opened 2022-10-09 08:49 UTC by linawolf

releases: main

2022-10-11 08:21 UTC, brotkrueml reviewed
Should the title be "for TYPO3 v12" instead of "for TYPO3 v11"?

2022-10-11 08:39 UTC, linawolf commented
It is a preport of the solution for v11, v12 is not solved completely yet

2022-10-11 08:41 UTC, brotkrueml commented
> It is a preport of the solution for v11, v12 is not solved completely yet

Ah, then the title is misleading. Anyway, as I made some changes to the v11 branch solution, these should be merged also into here?

2022-10-11 08:52 UTC, linawolf commented
> > It is a preport of the solution for v11, v12 is not solved completely yet
> 
> Ah, then the title is misleading. Anyway, as I made some changes to the v11 branch solution, these should be merged also into here?

Could you propose a better title?

2022-10-11 11:57 UTC, brotkrueml commented
> > > It is a preport of the solution for v11, v12 is not solved completely yet
> > 
> > 
> > Ah, then the title is misleading. Anyway, as I made some changes to the v11 branch solution, these should be merged also into here?
> 
> Could you propose a better title?

Well, as we have "backport" sometimes in the title what about "[Forwardport] [BUGFIX] Correct GitHub Linkhandler" with a description: "Forwardport from <the-commithash>"

2022-10-12 17:26 UTC, brotkrueml requested changes
Also the additional changed from the review process should be taken into account.

2022-10-12 17:26 UTC, brotkrueml commented on CHANGELOG.md
> +- Fix the Github Linkhandler for TYPO3 v11 (#133)
This does not apply to main/v12-compatible version?

2022-10-12 17:26 UTC, brotkrueml commented on Classes/LinkHandler/GithubLinkBuilder.php
> +    /**
Can we get rid of this docblock? It adds no value.

2022-10-12 17:26 UTC, brotkrueml commented on Classes/LinkHandler/GithubLinkBuilder.php
> +                '"' . $linkDetails['value'] . '" is not a valid Github issue number.',
```suggestion
                '"' . $linkDetails['value'] . '" is not a valid GitHub issue number.',
```

2022-10-13 15:38 UTC, linawolf commented on Classes/LinkHandler/GithubLinkBuilder.php
> +        array &$linkDetails,
```suggestion

    public function build(
        array &$linkDetails,
```

2022-10-13 15:38 UTC, linawolf commented on CHANGELOG.md
> +- Fix the Github Linkhandler for TYPO3 v11 (#133)
```suggestion
### Fixed
```

2022-10-13 16:07 UTC, brotkrueml reviewed
I am getting the error

     Class "T3docs\\Examples\\LinkHandler\\GitHubLinkHandler" not found

when opening the link browser. Looked into it but haven't found where it is configured.

2022-10-13 17:01 UTC, brotkrueml approved these changes

2022-10-13 17:08 UTC, merged