[FEATURE] Use alias for CustomCategoryProcessor
TYPO3-Documentation/t3docs-examples pull request #159
Opened 2022-10-21 13:39 UTC by brotkrueml

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/230

2022-10-21 16:15 UTC, linawolf approved these changes

2022-10-21 16:19 UTC, linawolf requested changes
This should be mentioned in the Changelog

2022-10-22 04:28 UTC, brotkrueml commented
> This should be mentioned in the Changelog

Done in https://github.com/TYPO3-Documentation/t3docs-examples/pull/160

2022-10-22 05:59 UTC, linawolf approved these changes

2022-10-22 05:59 UTC, merged