[TASK] Introduce phpstan and generate baseline
TYPO3-Documentation/t3docs-examples pull request #262
Opened 2024-05-01 17:58 UTC by linawolf

Depends on #261

2024-05-01 18:02 UTC, brotkrueml reviewed
You mix now again different things, you add phpstan and typo3-rector.

Also import namespaces instead using FQCNs.

2024-05-01 18:18 UTC, linawolf commented
As you can read in the description this Depends on https://github.com/TYPO3-Documentation/t3docs-examples/pull/261

2024-05-01 19:13 UTC, brotkrueml commented
Then please, set it as draft.

2024-05-02 05:39 UTC, linawolf commented
This branch is based on the one from #261 but contains a totally separated commit (https://github.com/TYPO3-Documentation/t3docs-examples/pull/262/commits/05fe7aca71765077bde6d1bdf78e3c7116e3fe9f) which can, if someone wants be reviewed independently. The descitsion is however up to the reviewer.

2024-05-03 07:38 UTC, linawolf commented
It is absolutely your right to decide like this

2024-05-03 10:37 UTC, sbuerk requested changes
on it to make minor adjustments ...

2024-05-03 15:13 UTC, sbuerk approved these changes

2024-05-04 06:17 UTC, merged